"""
report_generator.py
Turns a list of Finding objects into JSON, HTML, or PDF reports.
"""

import datetime
import json
import os
from collections import Counter

from utils import Severity, sort_findings

BEST_PRACTICES = [
    "Validate and sanitize all user input.",
    "Store secrets in environment variables or a secrets manager, never in code.",
    "Avoid eval() and exec(); prefer safe parsers (ast.literal_eval, json).",
    "Use parameterized queries for all database access.",
    "Hash passwords with bcrypt, scrypt, or Argon2 - never MD5/SHA-1.",
    "Use the 'secrets' module for security-sensitive randomness, not 'random'.",
    "Keep third-party dependencies updated and monitor for known CVEs.",
    "Apply the Principle of Least Privilege to services, files, and DB users.",
    "Handle exceptions securely without leaking stack traces or secrets to users.",
    "Never run production services with debug mode enabled.",
]


def _summary_counts(findings):
    counts = Counter(str(f.severity) for f in findings)
    for s in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"):
        counts.setdefault(s, 0)
    return counts


# --------------------------------------------------------------------------
# JSON
# --------------------------------------------------------------------------
def generate_json_report(findings, target_path, output_path, meta=None):
    findings = sort_findings(findings)
    counts = _summary_counts(findings)
    report = {
        "tool": "PySecure Auditor",
        "target": target_path,
        "generated_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "summary": {
            "total_findings": len(findings),
            "by_severity": dict(counts),
        },
        "meta": meta or {},
        "findings": [f.to_dict() for f in findings],
        "best_practices": BEST_PRACTICES,
    }
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    return output_path


# --------------------------------------------------------------------------
# HTML
# --------------------------------------------------------------------------
_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>PySecure Auditor Report</title>
<style>
  :root {{
    --bg: #0f1115; --panel: #171a21; --border: #262b36; --text: #e7e9ee;
    --muted: #9aa2b1; --accent: #5aa9ff;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; font-family: -apple-system, "Segoe UI", Roboto, Arial, sans-serif;
    background: var(--bg); color: var(--text); padding: 32px;
  }}
  h1 {{ margin: 0 0 4px 0; font-size: 24px; }}
  .subtitle {{ color: var(--muted); margin-bottom: 24px; font-size: 14px; }}
  .summary {{ display: flex; gap: 12px; margin-bottom: 28px; flex-wrap: wrap; }}
  .card {{
    background: var(--panel); border: 1px solid var(--border); border-radius: 10px;
    padding: 14px 20px; min-width: 110px;
  }}
  .card .num {{ font-size: 26px; font-weight: 700; }}
  .card .label {{ color: var(--muted); font-size: 12px; text-transform: uppercase;
    letter-spacing: .05em; }}
  table {{ width: 100%; border-collapse: collapse; background: var(--panel);
    border: 1px solid var(--border); border-radius: 10px; overflow: hidden; }}
  th, td {{ text-align: left; padding: 10px 12px; font-size: 13px;
    border-bottom: 1px solid var(--border); vertical-align: top; }}
  th {{ background: #1d212b; color: var(--muted); text-transform: uppercase;
    font-size: 11px; letter-spacing: .04em; }}
  tr:last-child td {{ border-bottom: none; }}
  .sev {{ display: inline-block; padding: 2px 10px; border-radius: 999px;
    font-weight: 700; font-size: 11px; color: #fff; }}
  code {{ background: #0d0f14; padding: 2px 6px; border-radius: 4px;
    font-size: 12px; color: #ffd28a; }}
  .file {{ color: var(--accent); }}
  .practices {{ margin-top: 32px; background: var(--panel); border: 1px solid var(--border);
    border-radius: 10px; padding: 20px 24px; }}
  .practices h2 {{ margin-top: 0; font-size: 16px; }}
  .practices li {{ margin-bottom: 6px; color: #cfd3dc; font-size: 13px; }}
  .empty {{ color: var(--muted); padding: 24px; text-align: center; }}
  footer {{ margin-top: 24px; color: var(--muted); font-size: 12px; }}
</style>
</head>
<body>
  <h1>PySecure Auditor Report</h1>
  <div class="subtitle">Target: {target} &nbsp;|&nbsp; Generated: {generated_at}</div>

  <div class="summary">
    {summary_cards}
  </div>

  {table_or_empty}

  <div class="practices">
    <h2>Recommended Best Practices</h2>
    <ul>{practices}</ul>
  </div>

  <footer>Generated by PySecure Auditor &mdash; static analysis only, does not
  replace manual review or dynamic testing.</footer>
</body>
</html>
"""

def generate_html_report(findings, target_path, output_path):
    findings = sort_findings(findings)
    counts = _summary_counts(findings)

    cards = ""
    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"):
        color = Severity[sev].color
        cards += (f'<div class="card"><div class="num" style="color:{color}">'
                   f'{counts[sev]}</div><div class="label">{sev}</div></div>')
    cards += (f'<div class="card"><div class="num">{len(findings)}</div>'
              f'<div class="label">Total</div></div>')

    if findings:
        rows = ""
        for f in findings:
            rows += (
                "<tr>"
                f'<td class="file">{_esc(f.file)}:{f.line}</td>'
                f'<td>{_esc(f.vulnerability)}</td>'
                f'<td><span class="sev" style="background:{f.severity.color}">'
                f'{f.severity}</span></td>'
                f'<td>{_esc(f.description)}</td>'
                f'<td>{_esc(f.recommendation)}</td>'
                f'<td><code>{_esc(f.code_snippet)}</code></td>'
                f'<td>{_esc(f.source)}</td>'
                "</tr>"
            )
        table = (
            "<table><thead><tr>"
            "<th>Location</th><th>Vulnerability</th><th>Severity</th>"
            "<th>Description</th><th>Recommendation</th><th>Code</th><th>Engine</th>"
            "</tr></thead><tbody>" + rows + "</tbody></table>"
        )
    else:
        table = '<div class="empty">No issues found. 🎉</div>'

    practices = "".join(f"<li>{_esc(p)}</li>" for p in BEST_PRACTICES)

    html = _HTML_TEMPLATE.format(
        target=_esc(target_path),
        generated_at=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        summary_cards=cards,
        table_or_empty=table,
        practices=practices,
    )
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    return output_path


def _esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


# --------------------------------------------------------------------------
# PDF (reportlab)
# --------------------------------------------------------------------------
def generate_pdf_report(findings, target_path, output_path):
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                     Table, TableStyle, ListFlowable, ListItem)

    findings = sort_findings(findings)
    counts = _summary_counts(findings)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=20)
    h2_style = ParagraphStyle("H2X", parent=styles["Heading2"], spaceBefore=14)
    body = ParagraphStyle("BodyX", parent=styles["BodyText"], fontSize=8, leading=10)
    cell = ParagraphStyle("CellX", parent=styles["BodyText"], fontSize=7.5, leading=9)

    doc = SimpleDocTemplate(output_path, pagesize=A4,
                             topMargin=18 * mm, bottomMargin=16 * mm,
                             leftMargin=14 * mm, rightMargin=14 * mm)
    story = []
    story.append(Paragraph("PySecure Auditor Report", title_style))
    story.append(Paragraph(
        f"Target: {_esc(target_path)}<br/>"
        f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        body))
    story.append(Spacer(1, 10))

    sum_data = [["Critical", "High", "Medium", "Low", "Info", "Total"],
                [counts["CRITICAL"], counts["HIGH"], counts["MEDIUM"],
                 counts["LOW"], counts["INFO"], len(findings)]]
    sum_table = Table(sum_data, hAlign="LEFT")
    sum_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1d212b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(sum_table)
    story.append(Spacer(1, 16))

    if findings:
        story.append(Paragraph("Findings", h2_style))
        table_data = [["Location", "Vulnerability", "Sev", "Description",
                        "Recommendation"]]
        for f in findings:
            table_data.append([
                Paragraph(_esc(f"{os.path.basename(f.file)}:{f.line}"), cell),
                Paragraph(_esc(f.vulnerability), cell),
                Paragraph(str(f.severity), cell),
                Paragraph(_esc(f.description), cell),
                Paragraph(_esc(f.recommendation), cell),
            ])
        t = Table(table_data, colWidths=[55, 90, 32, 150, 150], repeatRows=1)
        style_cmds = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1d212b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, 0), 8),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#dddddd")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]
        for i, f in enumerate(findings, start=1):
            style_cmds.append(("BACKGROUND", (2, i), (2, i),
                                colors.HexColor(f.severity.color)))
            style_cmds.append(("TEXTCOLOR", (2, i), (2, i), colors.white))
        t.setStyle(TableStyle(style_cmds))
        story.append(t)
    else:
        story.append(Paragraph("No issues found.", body))

    story.append(Spacer(1, 18))
    story.append(Paragraph("Recommended Best Practices", h2_style))
    story.append(ListFlowable(
        [ListItem(Paragraph(_esc(p), body)) for p in BEST_PRACTICES],
        bulletType="bullet"))

    doc.build(story)
    return output_path
